### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by youngmanuit** [dpedwards/xamarin-mobile-wallet#1]
Your project is very impressive. But there seems to be something wrong with documentation. Can you check and update it, please ?

**Comment by dpedwards** [comment]
Hi thanks for your message! Yes of course I can check and update the documentation(s) soon. If you cannot wait for the documentation of the XamarinWallet feel free and check this repository before: [https://github.com/dpedwards/dotnet-core-blockchain-advanced](https://github.com/dpedwards/dotnet-core-blockchain-advanced)

You have to execute the BlockChain (maybe the BlockChain Client if you want), BlockchainPaymentShop and the ProxyServer projects to use the XamarinWallet Android app.

If you have any further questions, please don't hesitate to ask me.
